#!/usr/bin/env bash

# Update package index
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Create a custom index file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx service
sudo service nginx restart
