#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01 server.
# Configures HAProxy to send traffic to web-01 and web-02 servers.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  janeamy-frontend
        bind *:80
        mode http
        default_backend jenny-backend
backend janeamy-backend
        balance roundrobin
        server 147866-web-01 100.25.220.231:80 check
        server 147866-web-02 107.23.92.187:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
