#!/usr/bin/env bash
# Bash script that creates an RSA key pair
# Generate key pair
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school
#Add passphrase to the private key
ssh-keygen -p -p "" -N "betty" -f ~/.ssh/school
